#!/usr/bin/env bash
# Quick reference for Maxon commands

echo "=== Maxon Bot Quick Reference ==="
echo ""
echo "📋 Preparation:"
echo "  cp .env.example .env"
echo "  # Edit .env and add MAX_ACCESS_TOKEN"
echo ""
echo "🚀 Start:"
echo "  docker-compose up -d"
echo ""
echo "✅ Verify:"
echo "  curl http://localhost:8000/health"
echo "  docker-compose logs -f maxon-bot"
echo ""
echo "🛑 Stop:"
echo "  docker-compose down"
echo ""
echo "🔄 Restart:"
echo "  docker-compose restart maxon-bot"
echo ""
echo "📊 Status:"
echo "  docker-compose ps"
echo ""
echo "📝 User commands (in Max Messenger):"
echo "  - Send time: 15:30"
echo "  - Send reminder text"
echo "  - /list (show reminders)"
echo "  - /del N (delete reminder N)"
echo ""
echo "📚 Documentation:"
echo "  - README.md (English)"
echo "  - LOCAL_SETUP.md (Русский)"
echo "  - VERIFICATION.md (Requirements check)"
echo "  - CI-CD.md (Production deployment)"
echo ""
